src/community/common/components/atoms/Button/StyledButton.ts
=> Fix/728: Button Border Getting Cropped Issue

src/community/common/components/molecules/VersionUpgradeBanner/VersionUpgradeBanner.tsx, src/community/common/components/templates/ContentLayout/ContentLayout.tsx, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/AddNewResourceFlow.tsx, src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/GeneralDetailsSection.tsx
=> Fix/499: Storage Limit Reached Indicator Issues

.gitmodules
=> Add submodule by command

package-lock.json, package.json, pages/_app.tsx, src/community/common/constants/configs.ts
=> Feat/40 : Hotjar integration for testing

package.json, pages/api/health.js
=> Added health route and patch version up

package-lock.json, package.json
=> hotfix: sign up layout import issue

next.config.mjs, package-lock.json
=> Feat: sso signin integration

next.config.mjs, pages/api/deleteFile.ts, src/community/common/api/FileHandleApi.ts, src/community/common/assets/languages/english/leaveModule.json, src/community/leave/components/molecules/ManagerLeaveModalContents/ManagerApproveLeaveModal/ManagerApproveLeaveModal.tsx, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx
=> ep-45: leave attachment download feature

i18n.ts
=> fix: translation issue

.gitignore, firebase.ts, package-lock.json, package.json, public/firebase-messaging-sw.js, src/community/common/components/templates/BaseLayout/BaseLayout.tsx, tsconfig.json
=> Feat/34: Push Notifications

src/community/common/components/organisms/Settings/Settings.tsx, src/community/common/utils/hooks/useRedirectHandler.ts
=> Feat/24: Removing email server setup from settings

firebase.ts, src/community/common/components/templates/ContentLayout/ContentLayout.tsx, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/GeneralDetailsSection.tsx
=> Feat/47: Removed Storage Banner From Enterprise

firebase.ts, src/community/common/utils/getDrawerRoutes.ts
=> Fix/44: Leave Requests Drawer Items

src/community/people/components/organisms/JobFamilyModals/TransferMembersModals/JobFamilyTransferMembersModal.tsx, src/community/people/components/organisms/JobFamilyModals/TransferMembersModals/JobTitleTransferMembersModal.tsx
=> Fix/60: Employee Transfering and Deleting Job Family and Job Title 

pages/index.tsx, src/community/common/components/molecules/ProfileMenu/ProfileMenu.tsx
=> Fix: credential login redirection issue

pages/community/signup.tsx, src/community/common/components/organisms/Forms/SignUpForm/setupSuperAdminForm/SetupSuperAdminForm.tsx, src/community/common/utils/validation.ts
=> Fix/49: signup validation added

src/community/people/api/JobFamilyApi.ts, src/community/people/utils/jobFamilyUtils/jobTitleUtils.ts
=> Hot Fix: Job Title Delete Issue

src/community/people/components/molecules/LoginCredentialsModal/LoginCredentialsModal.tsx, src/community/people/components/molecules/UserBulkUploadModals/UserBulkCsvUpload.tsx
[#581](https://github.com/rootcodelabs/skapp/issues/581)
[#740](https://github.com/rootcodelabs/skapp/issues/740)
- Fixed indentation issue when sharing credentials through slack,
- Fixed user bulk upload issue 
1.
=> fix: indentation issue and user bulk upload issue

next.config.mjs, src/community/common/assets/languages/english/peopleModule.json, src/community/common/utils/axiosInterceptor.ts, src/community/people/api/PeopleApi.ts, src/community/people/components/molecules/AddNewResourceModal/AddNewResourceModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/SystemPermissionSection/SystemPermissionForm.tsx
=> remove credential features

src/community/leave/components/molecules/CustomLeaveModals/AddLeaveAllocationModal/AddLeaveAllocationModal.tsx, src/community/leave/components/organisms/CustomLeaveModalController/CustomLeaveModalController.tsx
=> fix: resume flow bug

middleware.ts
=> Fix credential login flow issue

middleware.ts, next.config.mjs, src/community/common/constants/routes.ts, src/community/common/theme/theme.ts, src/community/common/utils/data/routes.ts
=> Feat/ Billing page

src/community/common/components/templates/BaseLayout/BaseLayout.tsx
=> Fix: Console log for testing

src/community/common/assets/languages/english/onboarding.json
=> feat: provider checker

src/community/common/assets/languages/english/peopleModule.json, src/community/people/components/molecules/AddNewResourceModal/AddNewResourceModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/SystemPermissionSection/SystemPermissionForm.tsx
=> feat: role limitation

src/community/common/components/molecules/InputField/InputField.tsx
=> fix: ui issues organization

src/community/people/components/molecules/AddNewResourceModal/AddNewResourceModal.tsx
=> Fix: quick add permission issue

pages/_app.tsx, pages/community/setup-organization.tsx, src/community/common/components/molecules/FullScreenLoader/FullScreenLoader.tsx
=> Feat: full screen loader

src/community/common/utils/data/routes.ts
=> Fix: billing settings access restriction removal

public/firebase-messaging-sw.js
=> Fix/34: Background Notification Increaseing Unread Msg Count

next.config.mjs, pages/community/settings/account.tsx, src/community/common/constants/routes.ts, src/community/common/utils/data/routes.ts
=> Hotfix: account setting selecting issue

src/community/common/assets/languages/english/onboarding.json
=> Feat/48: Translations for limiting users notification

src/community/common/assets/languages/english/leaveModule.json, src/community/leave/components/molecules/LeaveAllocation/LeaveAllocationEmptyScreen.tsx, src/community/leave/store/slices/leaveRequestFilterSlice.tsx
=> fix: my leave request translation issue and empty table style issue

src/community/common/components/molecules/DragAndDropField/styles.ts, src/community/leave/components/molecules/LeaveEntitlementModals/OverrideConfirmation/styles.ts, src/community/leave/components/molecules/LeaveEntitlementModals/UploadCsv/UploadCsv.tsx, src/community/leave/components/molecules/LeaveEntitlementModals/UploadCsv/styles.ts, src/community/leave/components/molecules/LeaveEntitlementTable/LeaveEntitlementTable.tsx, src/community/leave/utils/leaveEntitlement/uploadCsvUtils.test.ts, src/community/leave/utils/leaveEntitlement/uploadCsvUtils.ts
=> Fix/131: Leave Entitlement Bulk Upload Flow Issues

pages/community/people/individual.tsx, src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmergencyDetailsSection/EmergencyDetailsForm.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/EmploymentDetailsForm.tsx, src/community/people/components/organisms/AddNewResourceFlow/EntitlementsDetailsSection/EntitlementsDetailsForm.tsx, src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/PersonalDetailsForm.tsx, src/community/people/components/organisms/AddNewResourceFlow/SystemPermissionSection/SystemPermissionForm.tsx
- UI related design changes addressed 
1.
=> Fix: People module UI issues fixed

src/community/common/assets/languages/english/peopleModule.json, src/community/common/components/organisms/Forms/ResetPassword/ResetPasswordForm.tsx, src/community/people/components/molecules/PeopleTimeline/PeopleTimeline.tsx, src/community/people/components/molecules/PeopleTimeline/styles.ts, src/community/people/utils/peopleTimelineUtils.ts
[#179](https://github.com/SkappHQ/skapp-ep/issues/179)
[#176](https://github.com/SkappHQ/skapp-ep/issues/176)
-
1.
=> fix: setup organization wording and timeline style issues

pages/community/leave/types/[slug].tsx, src/community/leave/components/organisms/LeaveTypeForm/LeaveTypeForm.tsx, src/community/leave/utils/leaveTypes/LeaveTypeUtils.ts
=> Fix/116: Handle Leave Type Form Back Button Click

src/community/common/components/molecules/InputDate/InputDate.tsx, src/community/leave/components/molecules/CustomLeaveModals/EditLeaveAllocationModal/EditLeaveAllocationModal.tsx, src/community/leave/components/organisms/CustomLeaveModalController/CustomLeaveModalController.tsx
[#165](https://github.com/SkappHQ/skapp-ep/issues/165)
-
1.
=> Fix/165: calender and modal issue

pages/community/leave/types/[slug].tsx, src/community/common/assets/languages/english/leaveModule.json, src/community/common/components/molecules/Table/Table.tsx, src/community/common/components/molecules/Table/TablePagination.tsx, src/community/common/components/molecules/TableEmptyScreen/TableEmptyScreen.tsx
=> Fix/118: Leave Type Form UI Issues

src/community/leave/components/molecules/CustomLeaveAllocationsTable/CustomLeaveAllocationsTable.tsx, src/community/leave/components/organisms/CustomLeaveAllocationContent/CustomLeaveAllocationContent.tsx
=> fix: filter option issue

pages/_app.tsx, pages/community/leave/types/[slug].tsx, pages/community/leave/types/index.tsx, src/community/common/components/organisms/Drawer/styles.ts, src/community/leave/components/molecules/LeaveTypesTable/LeaveTypesTable.tsx, src/community/leave/components/molecules/UserPromptModals/UnsavedChangesModal/UnsavedChangesModal.tsx, src/community/leave/components/organisms/LeaveTypeForm/LeaveTypeForm.tsx, src/community/leave/store/slices/leaveTypeSlice.tsx, src/community/leave/utils/leaveTypes/LeaveTypeUtils.ts
=> Fix/116: Leave Type Form Back Button Click

src/community/common/components/atoms/Button/Button.tsx, src/community/common/components/templates/ContentLayout/ContentLayout.tsx
=> Fix/187: color changing when refreshing the page issue and Nan appearing on the dashboard issue

src/community/common/components/molecules/InputDate/CalendarHeader/CalendarHeader.tsx, src/community/common/components/molecules/InputDate/CalendarHeader/styles.ts, src/community/common/components/molecules/InputDate/InputDate.tsx, src/community/common/components/molecules/InputDate/styles.ts, src/community/leave/components/organisms/LeaveTypeForm/LeaveTypeForm.tsx
=> Fix/117: Input Date Year Can Be Hidden Now

src/community/people/utils/eChartOptions/jobFamilyOverviewChartOptions.ts
=> fix: hide chart legend for laptop screen

src/community/people/components/molecules/HolidayTable/HolidayTable.tsx, src/community/people/components/molecules/HolidayTable/styles.ts, src/community/people/components/molecules/SortByDropDown/SortByDropDown.tsx, src/community/people/components/molecules/SortByDropDown/styles.ts
…e sort by drop down related code to a new component
-
1.
=> Fix/234: Default Selected Year in Holiday Table is Current Year, Plus Moved the Sort By Drop Down Component Related Code To New Component

src/community/people/components/molecules/UserBulkUploadModals/UserBulkCsvDownload.tsx, src/community/people/hooks/useUserBulkConvert.ts, src/community/people/types/UserBulkUploadTypes.ts
=> Fix/233: Added New Columns to People Bulk Upload

src/community/people/components/organisms/AddNewResourceFlow/EmergencyDetailsSection/PrimaryDetailsSection.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmergencyDetailsSection/SecondaryDetailsSection.tsx, src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/ContactDetailsSection.tsx
=> Fix/241 When adding a full profile phone number and emergency contact details are not sending from the frontend

src/community/leave/components/molecules/LeaveEntitlementModals/DownloadCsv/DownloadCsv.tsx, src/community/leave/components/molecules/LeaveEntitlementModals/UploadCsv/UploadCsv.tsx, src/community/leave/utils/leaveEntitlement/leaveEntitlementUtils.ts
=> Fix/242: Leave Entitlement Bulk Upload Issues (BE Change Should Be Deployed First)

pages/_app.tsx
=> Fix: Maintainence mode issue

src/community/leave/components/molecules/LeaveEntitlementTable/LeaveEntitlementTable.tsx, src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Fix/220: Leave Entitlement Table Footer Issues

src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Fix: domain name reset issue

src/community/common/utils/getDrawerRoutes.ts, src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Fix/258: Leave Employee Leave Drawer Item Removed

src/community/leave/api/LeaveEntitlementApi.ts, src/community/leave/api/utils/QueryKeys.ts, src/community/leave/components/molecules/LeaveEntitlementTable/LeaveEntitlementTable.tsx, src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Fix/262: Exports All the Data in the Leave Entitltment Table

src/community/common/components/molecules/ColorPalette/ColorPalette.tsx
=> Fix/111: Color Palette Label Typography Color

src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/CareerProgressionDetailsSection.tsx
…changed, an error gets triggered
-
1.
=> Fix/218: Job Title Validation Error Get Triggered

src/community/people/components/organisms/AddNewResourceFlow/EmergencyDetailsSection/PrimaryDetailsSection.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmergencyDetailsSection/SecondaryDetailsSection.tsx, src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/ContactDetailsSection.tsx
=> fix/241: issue when adding phone and emergency contact details in employee full profile

.gitmodules
=> feat: submodule changes

src/community/people/components/molecules/PeopleTable/PeopleTable.tsx
=> fix: time manager permission issue

pages/community/people/directory/edit-all-information/[id].tsx, src/community/common/components/molecules/ProfileMenu/ProfileMenu.tsx, src/community/common/hooks/useGetProfileDetails.tsx, src/community/people/hooks/useGetEmployee.tsx
=> fix: data not changing when changing profiles issue fixed

src/community/people/hooks/useGetEmployee.tsx
=> removed console statements

src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/EmploymentDetailsSection.tsx, src/community/people/components/organisms/EmployeeData/EmployeeData.tsx
=> Fix/287: Employee Details in Employee View issues

src/community/common/components/atoms/Button/StyledButton.ts, src/community/leave/components/organisms/LeaveTypeForm/LeaveTypeForm.tsx
=> Hot Fix/ Trimmed Spaces from Leave Type

src/community/attendance/components/molecules/TimesheetDailyLogFilter/TimesheetDailyLogFilter.tsx, src/community/common/components/molecules/FilterButton/FilterButton.tsx, src/community/common/components/molecules/ItemSelector/ItemSelector.tsx, src/community/common/components/molecules/TeamSelector/TeamSelector.tsx, src/community/people/components/molecules/HolidayTable/HolidayTable.tsx, src/community/people/components/molecules/SortByDropDown/SortByDropDown.tsx
=> Fix/276: Button Moving on Hover Issue

src/community/common/components/templates/ContentLayout/ContentLayout.tsx, src/community/common/constants/configs.ts, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/GeneralDetailsSection.tsx
=> Fix/47: Storage Limit Exceeded Banner

pages/community/people/directory/edit-all-information/[id].tsx, src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/VisaDetailsSection.tsx, src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/FamilyDetailsSection.tsx
=> hotfix: prod issue in people info fixed

src/community/people/components/molecules/PeopleTable/PeopleTable.tsx
=> Fix: people directory employee redirection issue

middleware.ts, pages/community/leave/analytics/[id].tsx
=> fix: leave manager should not be able to access leave report

src/community/common/types/next-auth.ts
=> Feat/166: enterprise refresh token handling

pages/community/people/directory/edit-all-information/[id].tsx
=> fix: missing leave and time tab in people module

pages/community/leave/leave-requests.tsx, pages/community/timesheet/all-timesheets.tsx
=> fix: analytic redirection to the employee view issue fixed

middleware.ts, next.config.mjs, src/community/common/types/AuthTypes.ts, src/community/common/utils/data/routes.ts, src/community/common/utils/getDrawerRoutes.ts, src/community/configurations/types/UserRolesTypes.ts, src/community/configurations/utils/userRoles/apiUtils.ts, src/community/people/components/molecules/AddNewResourceModal/AddNewResourceModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/SystemPermissionSection/SystemPermissionForm.tsx, src/community/people/hooks/useGetEmployee.tsx, src/community/people/types/AddNewResourceTypes.ts, src/community/people/types/EmployeeTypes.tsx
=> feat: 110 - esign role api integration

src/community/leave/components/molecules/CustomLeaveModals/EditLeaveAllocationModal/EditLeaveAllocationModal.tsx
=> fix: resume flow not working in edit custom leave allocation

src/community/common/assets/languages/english/peopleModule.json, src/community/common/components/molecules/AreYouSureModal/AreYouSureModal.tsx, src/community/configurations/components/molecules/UnsavedTimeConfigChangesModal/UnsavedTimeConfigChangesModal.tsx, src/community/leave/components/molecules/CustomLeaveModals/UnsavedAddLeaveModal/UnsavedAddLeaveModal.tsx, src/community/leave/components/molecules/UserPromptModals/UnsavedChangesModal/UnsavedChangesModal.tsx, src/community/leave/components/organisms/UnsavedLeaveAllocationModal/UnsavedLeaveAllocationModal.tsx, src/community/people/components/molecules/TeamModals/UnsavedAddTeamModal/UnsavedAddTeamModal.tsx, src/community/people/components/molecules/TeamModals/UnsavedEditTeamModal/UnsavedEditTeamModal.tsx, src/community/people/components/organisms/JobFamilyModals/UserPromptModals/UnsavedChangesModal.tsx
=> Refactor/114: Using reusable are you sure modal

pages/community/people/directory/edit-all-information/[id].tsx, src/community/common/assets/Icons/InviteIcon.tsx, src/community/common/assets/languages/english/peopleModule.json, src/community/common/components/atoms/Button/Button.tsx, src/community/common/components/atoms/Button/StyledButton.ts, src/community/people/actions/PeopleDataPreprocessor.ts, src/community/people/api/PeopleApi.ts, src/community/people/api/utils/ApiEndpoints.ts, src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/components/molecules/ReinviteConfirmationModal/ReinviteConfirmationModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/EmploymentDetailsSection.tsx, src/community/people/store/slices/addNewEmployeeSlice.ts, src/community/people/types/SliceTypes.ts, src/community/people/types/StoreTypes.ts
=> Feat/124: send re invitation for the pending users

src/community/common/components/molecules/Table/Table.tsx
=> Fix: remove invalid logic from table component

pages/community/people/directory/edit-all-information/[id].tsx, src/community/common/assets/languages/english/peopleModule.json, src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/components/molecules/ReinviteConfirmationModal/ReinviteConfirmationModal.tsx
=> Hotfix: reinvitation flow modal and toast content changes

pages/community/dashboard/index.tsx, pages/community/people/directory/edit-all-information/[id].tsx, pages/community/people/individual.tsx, src/community/common/components/molecules/NotificationSettinngs/NotificationSettinngs.tsx, src/community/common/components/molecules/NotificationsPopup/NotificationsPopup.tsx, src/community/common/components/organisms/AppBar/AppBar.tsx, src/community/common/utils/getDrawerRoutes.ts, src/community/configurations/components/molecules/UserRolesTable/UserRolesTable.tsx, src/community/people/components/molecules/AddNewResourceModal/AddNewResourceModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/SystemPermissionSection/SystemPermissionForm.tsx
=> Feat/134: Module Restrictions according module roles 

src/community/common/components/organisms/Drawer/Drawer.tsx, src/community/common/utils/getDrawerRoutes.ts, src/community/people/components/molecules/ExpandedFilerSections/UserRolesSection.tsx
=> Feat/135: leave module restrictions

src/community/common/components/organisms/Drawer/Drawer.tsx, src/community/common/utils/getDrawerRoutes.ts, src/community/people/components/molecules/ExpandedFilerSections/UserRolesSection.tsx
=> main to dev

pages/community/people/individual.tsx, src/community/common/assets/languages/english/peopleModule.json, src/community/common/components/molecules/DropdownAutocomplete/DropdownAutocomplete.tsx, src/community/common/components/molecules/DropdownList/DropdownList.tsx, src/community/common/components/molecules/InputDate/InputDate.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/EmploymentDetailsSection.tsx, src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/GeneralDetailsSection.tsx
=> fix: style issues when employee view other employee details they appear editable

src/community/common/assets/languages/english/onboarding.json
=> Feat/1: work email validation

src/community/common/enums/CommonEnums.ts, src/community/configurations/components/molecules/UserRolesTable/UserRolesTable.tsx
=> Feat/320: Removed E signature from User Roles Table

middleware.ts
=> fix: hide integration page temporary from drawer

pages/community/people/directory/edit-all-information/[id].tsx, src/community/common/components/molecules/Table/styles.ts, src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/components/molecules/ReinviteConfirmationModal/ReinviteConfirmationModal.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/EmploymentDetailsSection.tsx
=> Fix/323: Pending invitees work email changing when the user cancels the confirmation the behavior is not as expected issue

pages/community/leave/analytics/[id].tsx, pages/community/timesheet/analytics/[id].tsx, src/community/common/types/CommonTypes.ts
=> Fix/459: The view full report button is available in the team timesheet analytics issue

src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/EmploymentDetailsForm.tsx
=> Hot Fix: Leave Entitlement is Available When the Leave Module is On 

pages/community/people/directory/edit-all-information/[id].tsx
=> Fix/486: Can View System Permission Section

pages/community/people/directory/edit-all-information/[id].tsx, src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Fix/305: User termination flow does not work as expected issue

package-lock.json, package.json
=> Papaparse version correction

pages/community/people/directory/edit-all-information/[id].tsx, src/community/people/components/organisms/AddNewResourceFlow/EmergencyDetailsSection/EmergencyDetailsForm.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/EmploymentDetailsForm.tsx, src/community/people/components/organisms/AddNewResourceFlow/EmploymentDetailsSection/EmploymentDetailsSection.tsx, src/community/people/components/organisms/AddNewResourceFlow/EntitlementsDetailsSection/EntitlementsDetailsForm.tsx, src/community/people/components/organisms/AddNewResourceFlow/EntitlementsDetailsSection/styles.ts, src/community/people/components/organisms/AddNewResourceFlow/SystemPermissionSection/SystemPermissionForm.tsx
=> Hot Fix: Button Icons, Removed Wrong Success Toast and fixed email validation issue when editing employment details

src/community/common/components/atoms/Button/Button.tsx, src/community/common/components/atoms/Button/StyledButton.ts, src/community/common/components/templates/ContentLayout/ContentLayout.tsx, src/community/common/utils/commonUtil.ts
https://github.com/user-attachments/assets/0247e530-7c30-4b9f-b08f-a4c56e9abe91
1.
=> Feat/555: Button Can Be Blinked Now

src/community/common/components/atoms/Button/StyledButton.ts
=> Feat/555: Added useMemo To Reduce Recalculating

src/community/common/utils/getDrawerRoutes.ts
=> hotfix: drawer setting page issue

src/community/common/components/molecules/CalendarDateRangePickersDay/CalendarDateRangePickersDay.tsx, src/community/common/utils/calendarDateRangePickerStyleUtils.ts, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx
=> Fix/324: Leave Indicator Calendar Date Picker

middleware.ts, next.config.mjs, src/community/common/assets/languages/english/common.json, src/community/common/components/organisms/Drawer/Drawer.tsx, src/community/common/components/organisms/Settings/Settings.tsx, src/community/common/components/templates/BaseLayout/BaseLayout.tsx, src/community/common/constants/routes.ts, src/community/common/enums/CommonEnums.ts, src/community/common/hooks/useSessionData.ts, src/community/common/utils/getDrawerRoutes.ts, src/community/common/utils/getEnterpriseDrawerRoutes.ts, src/fallback/common/store/commonStore.ts, src/fallback/common/utils/data/enterpriseRoutes.ts, src/fallback/common/utils/getEnterpriseDrawerRoutes.ts
=> Fix/649: Integration Page Rename

pages/community/dashboard/index.tsx, src/community/common/providers/TanStackProvider.tsx, src/community/common/utils/axiosInterceptor.ts
=> Hotfix: Version Mismatch Token Refresh Issue

src/community/common/components/molecules/CalendarDateRangePicker/CalendarDateRangePicker.tsx, src/community/common/components/molecules/DateRangePickersDay/styles.ts, src/community/common/utils/calendarDateRangePickerUtils.ts, src/community/leave/api/MyRequestApi.ts, src/community/leave/api/utils/QueryKeys.ts, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx, src/community/leave/store/slices/myRequestSlice.tsx, src/community/leave/types/SliceTypes.ts, src/community/leave/types/StoreTypes.ts, src/community/people/api/utils/QueryKeys.ts
=> Fix/302, 523, 552: Apply Leave Modal Related Bugs

next.config.mjs, pages/community/people/directory/edit/[id].tsx, src/community/people/components/molecules/DirectorySteppers/DirectorySteppers.tsx, src/community/people/components/molecules/EditSectionButtonWrapper/EditSectionButtonWrapper.tsx, src/community/people/components/organisms/DirectoryEditSectionWrapper/DirectoryEditSectionWrapper.tsx, src/community/people/components/organisms/EmergencyDetailsSection/EmergencyDetailsForm.tsx, src/community/people/components/organisms/EmergencyDetailsSection/SubSections/PrimaryContactDetailsSection.tsx, src/community/people/components/organisms/EmergencyDetailsSection/SubSections/SecondaryContactDetailsSection.tsx, src/community/people/components/organisms/PeopleFormSectionWrapper/PeopleFormSectionWrapper.tsx, src/community/people/components/organisms/PeopleFormSections/PeopleFormSections.tsx, src/community/people/components/organisms/PersonDetailsSection/PersonalDetailsForm.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/ContactDetailsSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/EducationalDetailsSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/FamilyDetailsSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/GeneralDetailsSections.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/HealthAndOtherDetailsSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/SocialMediaDetailsSection.tsx, src/community/people/components/template/PeopleDirectoryEdit/PeopleDirectoryEdit.tsx
=> feat: refactor people module

src/community/common/components/organisms/ProtectedContent/ProtectedContent.tsx, src/community/common/components/organisms/ProtectedContent/styles.ts, src/community/common/components/organisms/Settings/Settings.tsx, src/community/common/components/organisms/UnProtectedContent/UnProtectedContent.tsx, src/community/common/components/organisms/UnProtectedContent/styles.ts, src/community/common/components/templates/BaseLayout/BaseLayout.tsx, src/community/common/hooks/useSessionData.ts, src/community/common/utils/authUtils.ts
https://github.com/user-attachments/assets/0fbcc12f-707a-45e3-adf5-ac9f07914abd
1.
=> Fix/650: SSO Calendar Issues

src/community/common/components/molecules/Avatar/Avatar.tsx, src/community/common/components/molecules/AvatarGroup/AvatarGroupAvatar.tsx, src/community/common/components/organisms/Drawer/Drawer.tsx, src/community/leave/components/molecules/ManagerLeaveModalContents/ManagerApproveLeaveModal/ManagerApproveLeaveModal.tsx
=> Fix/713: Profile Picture Not Loading Issue

src/community/people/components/molecules/PeopleTable/PeopleTable.tsx
=> Fix/673: Job Title in People Table Word Break

src/community/leave/components/molecules/LeaveEntitlementModals/LeaveEntitlementBulkUploadSummary/LeaveEntitlementBulkUploadSummary.tsx, src/community/leave/components/organisms/LeaveEntitlementModalController/LeaveEntitlementModalController.tsx
…r log is downloaded anymore
https://github.com/user-attachments/assets/589f6a84-ba9b-49e5-9a2a-b8fdba4583b9
1.
=> Fix/426: Leave Bulk Upload Summary Error Count

src/community/leave/components/molecules/CustomLeaveAllocationForm/CustomLeaveAllocationForm.tsx
=> Fix/590: Custom Allocation Can Be Added To Active Leave Types Issues

src/community/common/providers/TanStackProvider.tsx
=> Hotfix: invalidate all the query cache after token refresh

src/community/common/components/molecules/DurationSelector/DurationSelector.tsx, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx, src/community/leave/utils/myRequests/applyLeaveModalUtils.ts, src/community/people/components/molecules/HolidayModals/AddEditHolidayModal/AddEditHolidayModal.tsx
=> Fix/204:  Add Holiday Modal Duration Selector Issues

src/community/common/components/molecules/Tabs/Tabs.tsx
=> Fix/731: Dashboard Issues

src/community/common/components/atoms/Button/StyledButton.ts, src/community/common/components/atoms/DescribedSelection/DescribedSelection.tsx
=> Hot Fix: Animation Related To Quick Setup Flow

pages/community/dashboard/index.tsx
=> Fix: unsual success toast appearing issue

src/community/common/components/templates/ContentLayout/ContentLayout.tsx
=> Fix: trial ended modal not closing issue

src/community/common/utils/__test__/calendarDateRangePickerStyleUtils.test.ts, src/community/common/utils/__test__/dateTimeUtils.test.ts, src/community/common/utils/__test__/getDrawerRoutes.test.ts, src/community/leave/utils/myRequests/leaveSummaryUtils.test.ts, src/community/people/utils/jobFamilyUtils/modalControllerUtils.test.ts
=> fix: unit test failure

package-lock.json, package.json
=> chore: update Next.js version to Next.js 14.2.25

src/community/common/components/molecules/DurationSelector/styles.ts, src/community/common/utils/calendarDateRangePickerStyleUtils.ts, src/community/common/utils/calendarDateRangePickerUtils.ts, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx, src/community/leave/types/MyRequests.ts, src/community/leave/utils/myRequests/applyLeaveModalUtils.ts
=> Fix/797: Leave Apply Validation

pages/community/leave/entitlements/carry-forward-balances.tsx, src/community/leave/components/molecules/LeaveCarryForwardModals/LeaveCarryForwardSyncConfirmation/LeaveCarryForwardSyncConfirmation.tsx, src/community/leave/components/molecules/LeaveCarryForwardModals/LeaveCarryForwardSyncConfirmation/styles.ts, src/community/leave/components/organisms/LeaveCarryForwardModalController/LeaveCarryForwardModalController.tsx, src/community/leave/store/slices/leaveCarryForwardModalSlice.tsx, src/community/leave/types/SliceTypes.ts, src/community/leave/types/StoreTypes.ts
=> Fix/444: Leave Carry Forward Sync Button Status Added

pages/api/auth/communityAuthOptions.ts, src/community/common/components/templates/ContentLayout/ContentLayout.tsx, src/community/common/constants/routes.ts, src/community/common/types/next-auth.ts, src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Fix/940: super admin/people can delete themselves issue

pages/_document.tsx
=> Feat: add Hotjar tracking script to _document.tsx

src/community/common/utils/getDrawerRoutes.ts
=> Fix/645: Integration Page Authorization

src/community/attendance/components/molecules/TimeSheetFilters/TimeSheetFilters.tsx
=> fix: Attendance Module - global filter doesnt work as expecetd

src/community/common/providers/TanStackProvider.tsx
=> Fix/447: Handle Mutation Trigger When There Is No Internet

src/community/common/constants/routes.ts, src/community/people/components/molecules/AddNewResourceModal/AddNewResourceModal.tsx
=> fix: changed route to add

src/community/leave/components/molecules/CustomLeaveModals/AddLeaveAllocationModal/AddLeaveAllocationModal.tsx, src/community/people/hooks/useEmployeeDetailsFormHandler.tsx, src/community/people/utils/peopleValidations.ts
[#449](https://github.com/rootcodelabs/skapp-ep/issues/449)
[#626](https://github.com/rootcodelabs/skapp-ep/issues/626)
-
1.
=> fix: custom leave allocation issue

src/community/common/components/molecules/Avatar/Avatar.tsx, src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/components/organisms/EmployeeData/EmployeeData.tsx
=> Fix/424: Console Logs For Debugging Data Missing After A While

src/community/common/components/molecules/ChangeBrandingSettingsModal/ChangeBrandingSettingsModal.tsx, src/community/common/components/molecules/DragAndDropField/DragAndDropField.tsx, src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx, src/community/people/utils/peopleValidations.ts
…nts for improved file handling and state management
-
1.
=> Fix/168: organization logo file missing issue

src/community/common/assets/languages/english/peopleModule.json, src/community/people/components/molecules/ExpandedFilerSections/EmployementSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/ContactDetailsSection.tsx, src/community/people/hooks/useContactDetailsFormHandlers.tsx, src/community/people/hooks/usePrimaryContactDetailsFormHandlers.tsx, src/community/people/hooks/useSecondaryContactDetailsFormHandlers.tsx
=> fix/335,667 changed toast message in quick add, removed active from filter and fixed phone number issue in people

src/community/common/components/templates/ContentLayout/ContentLayout.tsx
=> Fix/1018: User Limit Exceeded Modal

src/community/common/assets/languages/english/peopleModule.json, src/community/people/components/molecules/RouteChangeAreYouSureModal/RouteChangeAreYouSureModal.tsx, src/community/people/components/organisms/AccountSectionWrapper/AccountSectionWrapper.tsx, src/community/people/components/organisms/DirectoryAddSectionWrapper/DirectoryAddSectionWrapper.tsx, src/community/people/components/organisms/DirectoryEditSectionWrapper/DirectoryEditSectionWrapper.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/SocialMediaDetailsSection.tsx, src/community/people/hooks/usePreviousEmploymentDetailsFormHandlers.tsx, src/community/people/types/PeopleTypes.ts, src/community/people/utils/peopleValidations.ts
=> Fix: people bug issues

pages/index.tsx, src/community/common/components/templates/BaseLayout/BaseLayout.tsx, src/community/common/constants/stringConstants.ts, src/fallback/common/constants/stringConstants.ts
=> hotfix: home page redirection issue

package-lock.json, package.json, src/community/common/assets/languages/english/leaveModule.json, src/community/common/components/molecules/FilterButton/FilterButton.tsx, src/community/common/components/molecules/Table/styles.ts, src/community/leave/components/molecules/CarryForwardTable/CarryForwardTable.tsx, src/community/leave/components/molecules/CarryForwardTableHeader/CarryForwardTableHeader.tsx, src/community/leave/components/molecules/CarryForwardTableHeader/styles.ts, src/community/leave/components/molecules/CarryForwardTableRow/CarryForwardTableRow.tsx, src/community/leave/components/molecules/CarryForwardTableRow/styles.ts, src/community/leave/components/molecules/LeaveEntitlementTableHeader/LeaveEntitlementTableHeader.tsx, src/community/leave/components/molecules/LeaveEntitlementTableHeader/styles.ts, src/community/leave/components/molecules/LeaveEntitlementTableRow/LeaveEntitlementTableRow.tsx, src/community/leave/components/molecules/LeaveEntitlementTableRow/styles.ts, src/community/leave/components/molecules/LeaveTypeCard/styles.ts, src/community/leave/utils/CarryForwardUtils.tsx
=> Fix/418, 427, 442, 448, 999, 1050: Leave Entitlement Issues

src/community/common/hooks/useSessionData.ts, src/community/people/components/organisms/EmergencyDetailsSection/EmergencyDetailsForm.tsx, src/community/people/components/organisms/EmergencyDetailsSection/SubSections/PrimaryContactDetailsSection.tsx, src/community/people/components/organisms/EmergencyDetailsSection/SubSections/SecondaryContactDetailsSection.tsx, src/community/people/components/organisms/EmploymentFormSection/EmploymentDetailsForm.tsx, src/community/people/components/organisms/EmploymentFormSection/SubSections/CareerProgressDetailsSection.tsx, src/community/people/components/organisms/EmploymentFormSection/SubSections/EmploymentDetailsSection.tsx, src/community/people/components/organisms/EmploymentFormSection/SubSections/IdentificationDetailsSection.tsx, src/community/people/components/organisms/EmploymentFormSection/SubSections/PreviousEmploymentDetailsSection.tsx, src/community/people/components/organisms/EmploymentFormSection/SubSections/VisaDetailsSection.tsx, src/community/people/components/organisms/PeopleFormSections/PeopleFormSections.tsx, src/community/people/components/organisms/PersonDetailsSection/PersonalDetailsForm.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/ContactDetailsSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/EducationalDetailsSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/FamilyDetailsSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/GeneralDetailsSections.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/HealthAndOtherDetailsSection.tsx, src/community/people/components/organisms/PersonDetailsSection/SubSections/SocialMediaDetailsSection.tsx, src/community/people/components/organisms/SystemPermissionFormSection/SystemPermissionFormSection.tsx
=> Fix/1033, 1035: people manager can edit others profile issue and People Manager Should Not Be Able to Edit Their Own System Permissions issue

src/community/people/enums/PeopleEnums.ts, src/community/people/utils/peopleEditFlowUtils/personalDetailsChangesUtils.ts
=> fix/1092 linkedin issue and fixed issue in separated 

src/community/attendance/components/molecules/ClockInTable/ClockInTable.tsx, src/community/attendance/components/molecules/EmployeeTimesheetRequestTable/EmployeeTimesheetRequestTable.tsx, src/community/attendance/components/molecules/ManagerTimesheetRequestTable/ManagerTimesheetRequestTable.tsx, src/community/common/components/molecules/Table/Table.tsx, src/community/common/components/molecules/Table/TableFoot.tsx, src/community/configurations/components/molecules/ModuleRolesTable/ModuleRolesTable.tsx, src/community/leave/components/molecules/AvailabilityCalendar/OnLeaveModal.tsx, src/community/leave/components/molecules/CustomAllocationsReportTable/CustomAllocationsReportTable.tsx, src/community/leave/components/molecules/CustomLeaveAllocationsTable/CustomLeaveAllocationsTable.tsx, src/community/leave/components/molecules/LeaveRequests/LeaveRequests.tsx, src/community/leave/components/molecules/LeaveRequestsReportTable/LeaveRequestsReportTable.tsx, src/community/leave/components/molecules/LeaveTypesTable/LeaveTypesTable.tsx, src/community/leave/components/molecules/ManagerLeaveRequests/ManagerLeaveRequest.tsx, src/community/leave/components/molecules/PendingLeaveRequestTable/PendingLeaveRequestTable.tsx, src/community/leave/components/molecules/TeamAnalyticsLeaveHistoryTable/TeamAnalyticsLeaveHistoryTable.tsx, src/community/leave/components/molecules/UserLeaveHistory/UserLeaveHistory.tsx, src/community/people/components/molecules/HolidayTable/HolidayTable.tsx, src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/components/molecules/TeamsTable/TeamsTable.tsx, src/community/people/components/organisms/JobFamilyTable/JobFamilyTable.tsx
=> Refactor: Table Names as Enums

src/community/common/components/atoms/MenuItem/MenuItem.tsx, src/community/people/components/molecules/AddTeamMemberRow/AddTeamMemberRow.tsx
=> Fix/996, 997: Team Accessibility

src/community/common/components/atoms/Tooltip/Tooltip.tsx, src/community/common/components/molecules/ChangeBrandingSettingsModal/ChangeBrandingSettingsModal.tsx
=> Fix/960: Branding Settings Modal Accessibility

src/fallback/common/api/peopleApi.ts
=> Fix: community version runtime error

src/community/common/assets/languages/english/leaveModule.json, src/community/leave/components/molecules/LeaveSummary/LeaveSummary.tsx
=> Fix: leave apply modal avatar chip hovering issue

src/community/common/assets/languages/english/aria/common.json, src/community/common/components/atoms/IconButton/IconButton.tsx, src/community/common/components/templates/ContentLayout/ContentLayout.tsx, src/community/leave/components/molecules/ManagerLeaveRequestFilterByBtn/MangerLeaveRequestFilterByBtn.tsx, src/community/leave/components/molecules/ManagerLeaveRequests/ManagerLeaveRequest.tsx
=> Fix/1194, 1195: All Leave Requests Accessibility

src/community/common/utils/getDrawerRoutes.ts
=> hotfix: drawer issue in esign configuration

src/community/common/enums/KeyboardEnums.ts, src/community/common/utils/keyboardUtils.ts
I just wanted to highlight why I used this approach—if accessibility rules change in the future (like using a different key to trigger events), we’ll only need to update them once in the utility function. That change will automatically apply everywhere the function is used, which makes things easier to maintain and keeps everything consistent.
=> Hot Fix: Keyboard Utils

src/community/common/components/organisms/Drawer/Drawer.tsx, src/community/common/components/organisms/Drawer/styles.ts, src/community/common/enums/KeyboardEnums.ts, src/community/common/utils/keyboardUtils.ts
=> Fix/942, 1107: Drawer Accessibility Issues

src/community/configurations/api/timeConfigurationApi.ts
=> Fix/1165: Time configs - API Failing when the user navigates to page

src/community/common/components/organisms/ContentWithDrawer/ContentWithDrawer.tsx, src/community/common/components/organisms/ContentWithoutDrawer/ContentWithoutDrawer.tsx, src/community/common/utils/keyboardUtils.ts
=> Fix/1180: Skip to Main Content Link

src/community/common/utils/getDrawerRoutes.ts
=> hotfix: esign drawer issue

src/community/attendance/components/molecules/ClockInTable/ClockInTable.tsx, src/community/attendance/components/molecules/EmployeeTimesheetRequestTable/EmployeeTimesheetRequestTable.tsx, src/community/attendance/components/molecules/ManagerTimesheetRequestTable/ManagerTimesheetRequestTable.tsx, src/community/common/enums/Table.ts, src/community/configurations/components/molecules/ModuleRolesTable/ModuleRolesTable.tsx, src/community/configurations/components/molecules/UserRolesTable/UserRolesTable.tsx, src/community/leave/components/molecules/AvailabilityCalendar/OnLeaveModal.tsx, src/community/leave/components/molecules/CustomAllocationsReportTable/CustomAllocationsReportTable.tsx, src/community/leave/components/molecules/CustomLeaveAllocationsTable/CustomLeaveAllocationsTable.tsx, src/community/leave/components/molecules/LeaveRequests/LeaveRequests.tsx, src/community/leave/components/molecules/LeaveRequestsReportTable/LeaveRequestsReportTable.tsx, src/community/leave/components/molecules/LeaveTypesTable/LeaveTypesTable.tsx, src/community/leave/components/molecules/ManagerLeaveRequests/ManagerLeaveRequest.tsx, src/community/leave/components/molecules/PendingLeaveRequestTable/PendingLeaveRequestTable.tsx, src/community/leave/components/molecules/TeamAnalyticsLeaveHistoryTable/TeamAnalyticsLeaveHistoryTable.tsx, src/community/leave/components/molecules/UserLeaveHistory/UserLeaveHistory.tsx, src/community/people/components/molecules/HolidayTable/HolidayTable.tsx, src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/components/molecules/TeamsTable/TeamsTable.tsx, src/community/people/components/organisms/JobFamilyTable/JobFamilyTable.tsx
=> Hotfix: Community Import Issue

src/community/common/components/molecules/Table/Table.tsx, src/community/common/components/molecules/Table/TableBody.tsx, src/community/common/components/molecules/Table/TableHead.tsx, src/community/people/components/molecules/HolidayTable/HolidayTable.tsx, src/community/people/components/molecules/PeopleTable/PeopleTable.tsx, src/community/people/utils/holidayUtils/holidayTableUtils.ts
=> Fix/212: Table Checkbox Selection

src/community/common/assets/languages/english/aria/common.json, src/community/common/components/organisms/ContentWithDrawer/ContentWithDrawer.tsx, src/community/common/components/organisms/ContentWithoutDrawer/ContentWithoutDrawer.tsx
=> Fix/1349: Skip to Main Content

src/community/common/assets/languages/english/common.json, src/community/common/assets/languages/english/leaveModule.json, src/community/leave/components/molecules/LeaveEntitlementModals/UploadCsv/UploadCsv.tsx, src/community/leave/components/molecules/ManagerLeaveModalContents/ManagerApproveLeaveModal/ManagerApproveLeaveModal.tsx, src/community/leave/types/LeaveRequestTypes.ts, src/community/leave/utils/LeavePreprocessors.ts
=> Fix/1069: Leave Duration Count

src/community/common/assets/languages/english/aria/common.json, src/community/common/components/atoms/Button/Button.tsx, src/community/common/components/atoms/Button/StyledButton.ts, src/community/common/components/templates/OnboardingLayout/OnboardingLayout.tsx
=> Fix/1332: SignIn Hover Accessibility

src/community/common/components/organisms/ContentWithDrawer/ContentWithDrawer.tsx, src/community/common/components/organisms/ContentWithoutDrawer/ContentWithoutDrawer.tsx
=> Hot Fix: Main Content Stylings

src/community/attendance/components/molecules/ClockWidget/ClockWidget.tsx, src/community/attendance/components/molecules/PlayButton/PlayButton.tsx, src/community/attendance/components/molecules/Timer/Timer.tsx, src/community/common/assets/languages/english/aria/attendance.json, src/community/common/assets/languages/english/aria/people.json, src/community/common/components/atoms/Tooltip/Tooltip.tsx, src/community/common/components/molecules/DropDownSearch/DropDownSearch.tsx, src/community/common/components/molecules/ToastMessage/ToastMessage.tsx, src/community/common/components/organisms/AppBar/AppBar.tsx, src/community/people/components/molecules/AddTeamMemberRow/AddTeamMemberRow.tsx
=> Fix/1102, 1385, 1380, 1383, 963 : Accessibility

src/community/common/regex/regexPatterns.ts, src/community/people/components/molecules/HolidayModals/UploadHolidayBulk/UploadHolidayBulk.tsx, src/community/people/utils/directoryUtils/holidayBulkUploadUtils/uploadHolidayBulkModalUtils.ts
=> Fix/1390: Holiday Bulk Upload Date Format

src/community/attendance/components/molecules/AttendanceCard/AttendanceCard.tsx, src/community/common/components/molecules/Table/Table.tsx, src/community/common/components/molecules/Table/styles.ts
=> Fix/1304: Accessibility Issues

src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Hotfix: termianation issue

src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Hotfix: termination prodissue

src/community/common/assets/languages/english/aria/leave.json, src/community/common/components/atoms/Button/Button.tsx, src/community/common/components/atoms/Icon/Icon.tsx, src/community/common/components/atoms/TextArea/TextArea.tsx, src/community/common/components/atoms/Tooltip/Tooltip.tsx, src/community/common/components/molecules/AvatarChip/AvatarChip.tsx, src/community/common/components/molecules/Dropdown/Dropdown.tsx, src/community/leave/components/molecules/LeaveEntitlementBalanceCard/LeaveEntitlementBalanceCard.tsx, src/community/leave/components/molecules/MyLeaveRequestsModals/ApplyLeaveModal/ApplyLeaveModal.tsx, src/community/leave/components/molecules/TeamAvailabilityCard/TeamAvailabilityCard.tsx
=> Hot-fix/ Screen Reader Demo Fixes

src/community/common/components/atoms/Tooltip/Tooltip.tsx, styles/global.css
=> Fix/837, 960: Quick Setup Tooltip

src/community/common/components/atoms/Tooltip/Tooltip.tsx, src/community/common/components/molecules/ColorInputField/ColorInputField.tsx
=> Hot Fix: Tooltip

src/community/people/components/molecules/EditInfoCard/EditInfoCard.tsx
=> Develop user terminate bugfix

pages/_error.tsx
=> Fix/1364: when something went wrong occurs back to home button does not work

src/community/common/theme/theme.ts, src/community/common/theme/themesData.ts, src/community/common/utils/commonUtil.ts, src/community/leave/components/molecules/AttachmentSummary/AttachmentSummary.tsx
=> Feat/1296: Leave Request Attachments Employee Downloadable

src/community/common/assets/languages/english/aria/common.json, src/community/common/components/molecules/ColorPalette/ColorPalette.tsx, src/community/common/components/molecules/EmojiPicker/EmojiPicker.tsx, src/community/configurations/components/organisms/RestrictedUserRolesModal/RestrictedUserRolesModal.tsx, src/community/leave/components/molecules/CustomLeaveAllocationsTable/CustomLeaveAllocationsTable.tsx, src/community/leave/components/molecules/LeaveEntitlementTable/LeaveEntitlementTable.tsx, src/community/people/components/molecules/PeopleTimeline/PeopleTimeline.tsx, src/community/people/components/molecules/PeopleTimeline/styles.ts
=> Fix/1485, 1492, 596, 595, 1469, 1472, 1272: Action Data Added to Leave Custom Allocation Table Data

src/community/common/regex/regexPatterns.ts, src/community/people/utils/directoryUtils/holidayBulkUploadUtils/uploadHolidayBulkModalUtils.ts
=> Fix/1390: Holiday Bulk Upload

src/community/common/components/molecules/AvatarGroup/AvatarGroupAvatar.tsx
=> Fix/713: Profile Picture Missing

src/community/attendance/components/molecules/ClockWidget/ClockWidget.tsx, src/community/attendance/components/molecules/Timer/Timer.tsx, src/community/attendance/components/molecules/Timer/styles.ts, src/community/common/components/atoms/Button/StyledButton.ts, src/community/common/components/atoms/ToggleSwitch/styles.ts, src/community/common/components/molecules/EmojiPicker/styles.ts, src/community/common/components/molecules/InputDate/InputDate.tsx, src/community/common/components/organisms/Drawer/Drawer.tsx, src/community/common/theme/theme.ts, src/community/leave/components/molecules/LeaveDashboardChips/AwayChip.tsx, src/community/leave/components/molecules/LeaveDashboardChips/HolidayChip.tsx
=> Fix/1441, 1443, 1444, 1445, 1474, 1494, 1493: Color Contrast Enhanced and Drawer Accessibility

src/community/common/components/atoms/Chips/IconChip.tsx/IconChip.tsx, src/community/common/components/molecules/AdvancedFilterButton/AdvancedFilterButton.tsx, src/community/common/components/molecules/FilterButton/styles.ts, src/community/leave/components/molecules/CustomLeaveAllocationsTable/CustomLeaveAllocationsTable.tsx, src/community/people/components/molecules/PeopleTimeline/PeopleTimeline.tsx
=> Fix/1305, 1543, 1245: Advance Filter Button Keyboard Accessibility

pages/community/leave/entitlements/carry-forward-balances.tsx, src/community/common/hooks/useBlockPageReload/useBlockPageReload.tsx
=> Fix/1243: Leave Carry Forward Page Refresh

src/community/common/components/molecules/DragAndDropField/DragAndDropField.tsx
=> fix/629,642 : custom inline error messages for larger files & unsupported file type

frontend/src/community/common/components/organisms/Modal/styles.ts, frontend/src/community/common/constants/commonConstants.ts
=> Fix/1541: contacts with longer names trucation

frontend/src/community/attendance/components/molecules/ClockInButton/ClockInButton.tsx, frontend/src/community/attendance/components/molecules/ClockWidget/ClockWidget.tsx, frontend/src/community/attendance/components/molecules/ClockWidget/styles.ts, frontend/src/community/attendance/components/molecules/PlayButton/PlayButton.tsx, frontend/src/community/attendance/components/molecules/PlayButton/styles.ts, frontend/src/community/common/components/atoms/Button/Button.tsx, frontend/src/community/common/components/organisms/AppBar/AppBar.tsx, frontend/src/community/common/components/organisms/AppBar/styles.ts, frontend/src/community/common/theme/theme.ts
Addressed Sonarqube issues as well and the accessibility issues
=> Fix/1442: Clock Widget Accessibility Issue

frontend/src/community/common/assets/languages/english/onboarding.json
First name → First Name
Last name → Last Name
=> fix: 611 - Apply title case to form labels on Super Admin Setup page

backend/src/main/java/com/skapp/community/common/util/DateTimeUtils.java, backend/src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
=> fix: update email deletion prefix to include timestamp

frontend/pages/index.tsx, frontend/src/community/common/utils/axiosInterceptor.ts
=> Hotfix: Root url redirection issue

frontend/pages/index.tsx, frontend/src/community/common/utils/axiosInterceptor.ts
=> Hotfix: redirection issue solution reimplementation

frontend/src/community/common/components/molecules/InputPhoneNumber/InputPhoneNumber.tsx, frontend/src/community/common/hooks/useGetProfileDetails.tsx, frontend/src/community/people/components/organisms/AddNewResourceFlow/EmergencyDetailsSection/PrimaryDetailsSection.tsx, frontend/src/community/people/components/organisms/AddNewResourceFlow/EmergencyDetailsSection/SecondaryDetailsSection.tsx, frontend/src/community/people/components/organisms/AddNewResourceFlow/PersonalDetailsSection/ContactDetailsSection.tsx, frontend/src/community/people/components/organisms/PersonDetailsSection/SubSections/ContactDetailsSection.tsx, frontend/src/community/people/hooks/useDetectChange.tsx, frontend/src/community/people/hooks/useDetectProfileChange.tsx, frontend/src/community/people/hooks/useGetDefaultConuntryCode.test.tsx, frontend/src/community/people/hooks/useGetDefaultCountryCode.tsx, frontend/src/community/people/hooks/useGetEmployee.test.tsx, frontend/src/community/people/hooks/useGetEmployee.tsx, frontend/src/community/people/hooks/usePrimaryContactDetailsFormHandlers.test.tsx, frontend/src/community/people/hooks/usePrimaryContactDetailsFormHandlers.tsx, frontend/src/community/people/hooks/useSecondaryContactDetailsFormHandlers.test.tsx, frontend/src/community/people/hooks/useSecondaryContactDetailsFormHandlers.tsx
=> Feat: Add Contact Number to org setup

frontend/pages/community/leave/entitlements/carry-forward-balances.tsx, frontend/src/community/common/hooks/useBlockPageReload/useBlockPageReload.tsx
=> Fix/1243: Leave Carry Forward Sync Reload

frontend/src/community/common/components/molecules/FilterButton/FilterButton.tsx
=> Fix/1473: Leave Allocaiton Filter

frontend/src/community/common/assets/languages/english/aria/common.json, frontend/src/community/common/components/atoms/Pagination/Pagination.tsx, frontend/src/community/common/components/molecules/SearchBox/SearchBox.tsx, frontend/src/community/leave/components/molecules/LeaveEntitlementTable/LeaveEntitlementTable.tsx
=> Fix/1828: Leave Allocation Screen Reader Improvements

frontend/src/community/common/components/organisms/ContentWithDrawer/styles.ts, frontend/src/community/common/utils/dateTimeUtils.ts, frontend/src/community/leave/components/molecules/LeaveEntitlementTable/LeaveEntitlementTable.tsx
…n LeaveEntitlementTable
-
1.
-
=> Hot Fix: Leave Entitlement Table Past Year Empty View

frontend/pages/community/leave/leave-requests.tsx, frontend/src/community/common/components/molecules/AutocompleteSearch/PeopleAndTeamAutocompleteSearch.tsx, frontend/src/community/common/components/molecules/AutocompleteSearch/styles.ts
…ch for improved employee and team selection
-
1.
-
=> Fix/1465: All Leave Requests Search Bar

frontend/src/community/attendance/components/molecules/TimesheetTableHeader/TableHeaderFill.tsx, frontend/src/community/leave/components/molecules/LeaveEntitlementsReportsTable/LeaveEntitlementsReportsTable.tsx, frontend/src/community/leave/components/molecules/TimesheetTableRow/TimesheetTableRowFill.tsx
…EntitlementsReportsTable
-
1.
-
=> Hotfix: Leave Reports Table Build Fail

backend/src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveRequestRepositoryImpl.java
=> fix: add team filtering to leave request query

backend/src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
=> fix: improve readability of password validation logic in AuthServiceImpl

frontend/src/community/common/components/atoms/SwitchRow/SwitchRow.tsx, frontend/src/community/common/components/molecules/KebabMenu/KebabMenu.tsx, frontend/src/community/common/components/organisms/Modal/Modal.tsx, frontend/src/community/common/components/templates/FullPageContainerLayout/FullPageContainerLayout.tsx, frontend/src/community/common/types/MoleculeTypes.ts
=> fix/1759,1802,2148,2149,2150,2151,2152 : unauthorized detail page issue & esign screen reader issues

frontend/src/community/common/assets/languages/english/aria/common.json, frontend/src/community/common/components/templates/ContentLayout/ContentLayout.tsx
=> fix/1887,1888,1890,2153 : esign accessibility issues

frontend/next.config.mjs, frontend/src/community/common/assets/languages/english/configurations.json, frontend/src/community/configurations/components/molecules/ModuleRolesTable/ModuleRolesTable.tsx, frontend/src/community/configurations/components/molecules/UserRolesTable/UserRolesTable.tsx, frontend/src/community/configurations/data/esignatureModuleRolesTableData.json
=> fix/1978,2042,2051 : esign roles page issue, skeleton loaders for esign pages and contact names character issues

frontend/src/community/common/components/templates/FullPageContainerLayout/FullPageContainerLayout.tsx
=> fix/1885,1887,1888,2152 : inbox, contact and document accessibility issues

frontend/src/community/people/components/organisms/EmployeeData/EmployeeData.tsx
=> Fix/2212 email search special chars 

frontend/src/community/people/components/molecules/PeopleTable/PeopleTable.tsx
=> fix: job title issue in people table

backend/src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
=> fix: # 1912 - Shifting supervisors from primary to secondary

frontend/next.config.mjs, frontend/package-lock.json, frontend/package.json
=> Chore/Remove AWS SDK package

frontend/src/community/common/utils/calendarDateRangePickerUtils.ts
=> Fix/2214: Apply Leave Range With Holiday

frontend/src/community/people/hooks/useSystemPermissionFormHandlers.tsx, frontend/src/community/people/store/slices/peopleSlice.tsx, frontend/src/community/people/types/SliceTypes.ts, frontend/src/community/people/types/StoreTypes.ts
=> feat: add superAdminCount state management to people slice and hooks

frontend/src/community/leave/utils/myRequests/applyLeaveModalUtils.ts
=> Fix/2214: Apply Leave Range DIsable Options

frontend/src/community/people/api/HolidayApi.ts
=> Hotfix: Prettier Formatting

frontend/src/community/common/utils/getDrawerRoutes.ts
=> Fix: Sidebar label updated for Leave Employee users

frontend/src/community/people/components/molecules/TeamsTable/TeamsTable.tsx
=> Fix: People manager can see add teams button issue

frontend/src/community/common/assets/Icons/CloseIcon.tsx
=> fix/2261,2331,2332 : Decline chip is incorrectly identified as a button on hover, Add signature modal UI issue & minimum color contrast ratio issues

frontend/src/community/common/components/molecules/DragAndDropField/DragAndDropField.tsx
=> fix/2011,2345,2365,2366,: enhance quick setup visibility logic and update envelope status

backend/src/main/java/com/skapp/community/peopleplanner/payload/request/EmployeeQuickAddDto.java, backend/src/main/java/com/skapp/community/peopleplanner/service/RolesService.java, backend/src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java, backend/src/main/java/com/skapp/community/peopleplanner/service/impl/RolesServiceImpl.java
=> feat: add default employee roles for quick add functionality

frontend/src/community/common/assets/languages/english/aria/people.json, frontend/src/community/people/components/organisms/JobFamilyTable/JobFamilyTable.tsx
=> Fix/2192 people manager job families UI issue

frontend/src/community/people/components/organisms/EmploymentFormSection/EmploymentDetailsForm.tsx, frontend/src/community/people/components/organisms/EmploymentFormSection/SubSections/EmploymentDetailsSection.tsx, frontend/src/community/people/types/PeopleEditTypes.ts
=> fix/2199 added Google domain validation for work email in people full profile add

frontend/src/community/common/components/molecules/KebabMenu/KebabMenu.tsx
=> fix/2314,2376 : kebab menu UI issues

frontend/src/community/people/components/molecules/AddNewResourceModal/AddNewResourceModal.tsx, frontend/src/community/people/hooks/useGeneralDetailsFormHandlers.tsx
…eneralDetailsFormHandlers
-
1.
-
=> Fix/ remove name field validations

backend/src/main/java/com/skapp/community/common/payload/request/UpdateOrganizationRequestDto.java, backend/src/main/java/com/skapp/community/leaveplanner/repository/LeaveEntitlementDao.java, backend/src/main/java/com/skapp/community/leaveplanner/repository/LeaveEntitlementRepository.java, backend/src/main/java/com/skapp/community/leaveplanner/repository/impl/LeaveEntitlementRepositoryImpl.java, backend/src/main/java/com/skapp/community/leaveplanner/service/impl/LeaveEntitlementServiceImpl.java
(https://github.com/SkappHQ/skapp/issues/#1708) 
-
1.
-
=> fix: #1708, #2029 add methods to retrieve employee leave entitlements and improve leave entitlement retrieval logic

backend/src/main/java/com/skapp/community/common/service/impl/AuthServiceImpl.java
=> Fix/2513: log improvements

backend/src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
=> feat: add user cache invalidation logic after employee operations

backend/src/main/java/com/skapp/community/peopleplanner/service/impl/RolesServiceImpl.java
=> hotfix/add INVOICE_NONE to valid invoice roles in RolesServiceImpl

backend/src/main/java/com/skapp/community/common/type/EmailBodyTemplates.java, backend/src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleEmailServiceImpl.java, backend/src/main/resources/community/templates/email/email-templates.yml
=> feat: microsoft-email-templates

backend/src/main/java/com/skapp/community/peopleplanner/service/impl/JobServiceImpl.java
=> feat: remaining-context-fields

frontend/src/community/common/constants/routes.ts
=> fix: update invoice route to allInvoices

backend/src/main/java/com/skapp/community/common/model/User.java, backend/src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java
=> feat: implement user language management and add country/language enums

frontend/src/community/common/assets/Icons/DueIndicatorIcon.tsx, frontend/src/community/common/components/atoms/Icon/Icon.tsx
=> fix: add DueIndicatorIcon and update Icon mapping

frontend/src/community/common/theme/themeSelector.ts
=> Feat/tailwind color switcher for core fe 

backend/src/main/java/com/skapp/community/peopleplanner/service/impl/PeopleServiceImpl.java, backend/src/main/resources/community/templates/email/en/main-template-v1.html
=> feat: api-for-user-auth-pic

backend/src/main/java/com/skapp/community/common/util/Validation.java
=> fix: update address validation regex to allow additional characters
